server:
    port: 80
    #指定发布的目录
    context-path: /
    error:
      #always,on-trace-param
      include-stacktrace: always
https:
    port: 443

logging:
    config: classpath:logback-spring.xml

multipart.max-file-size: 50Mb
multipart.max-request-size: 100Mb

#自定义配置    
com.yjh:
    site: #冒号后面必须带一个空格
        host: http://www.usambl.com
        #静态资源服务器
        staticHost: http://www.usambl.com
        whiteDomainList: localhost,usambl.com
        siteDirPath: 
        uploadDir: upload/
        session: session_
        prefix: oumu
        coverCharge: 0 #提现手续费
        #报名推荐积分
        fractionA: 0
        #教练详情页分享积分
        fractionB: 0
        #二维码分享积分
        fractionC: 0
        EBusinessID: 1375771
        AppKey: ba49f178-60ba-4c93-b6d9-c13dd521a090
spring:
    aop.proxy-target-class: false
    http:
        encoding:
            # the encoding of HTTP requests/responses
            charset: utf8
            # enable http encoding support
            enabled: true
    datasource:
        name: mbl_shop
        url: jdbc:mysql://rm-wz928a9jr690875b7qo.mysql.rds.aliyuncs.com/mbl_shop?useUnicode=true&amp;characterEncoding=utf8
        username: mbl
        password: mbl123!!!
        #name: shop_test
        #url: jdbc:mysql://192.168.51.100:3306/test_shop?useUnicode=true&amp;characterEncoding=utf8
        #username: root
        #password: 1234
        #name: test_shop
        #url: jdbc:mysql://rm-wz9a201k95d10z656o.mysql.rds.aliyuncs.com/test_shop?useUnicode=true&amp;characterEncoding=utf8
        #username: derlp
        #password: Leoxu138
        
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        connectionInitSqls: set names utf8mb4
    mvc:
        view:
            prefix: /static/
            suffix: .html
        static-path-pattern: /**
    #freemarker:
        #cache: false
        #request-context-attribute: request
        #suffix: .html
    #thymeleaf:
      #cache: false
      #template-resolver-order: 0
    redis:
        host: 127.0.0.1
        password: 
        notify-keyspace-events: true
        port: 6379